### PR TITLE
Angular Material for V 11 Update

### PR DESCRIPTION
**Pull request by bhushangahire**

### CODE REVIEW

**Comment by mgechev** [comment]
@bhushangahire you'd have to sign the CLA so we can move forward with merging the PR.

**Comment by bhushangahire** [comment]
I did already.

**Comment by bhushangahire** [comment]
@googlebot I signed it!

**Comment by geromegrignon** [comment]
related to #125 (to be closed once this PR is merged)

**Comment by bhushangahire** [comment]
@mgechev all check are passed. You can merge now.

**Review by mgechev — APPROVED** [review]

**Pull request merged**
